// BITE.co Frontend Configuration — auto-generated by Terraform
// Do NOT edit this file manually; edit frontend/config.js.tpl instead.
const CONFIG = {
  AUTH_URL:     'https://${alb_dns}',
  USUARIOS_URL: 'https://${alb_dns}',
  CLOUD_URL:    'https://${alb_dns}',
  REPORTES_URL: 'https://${alb_dns}',
  SEGURIDAD_URL:'https://${alb_dns}',
};
