# Generated by Django 4.2.16 on 2026-04-09 21:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ANALYST', 'Analyst')], default='ANALYST', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='projects.empresa')),
            ],
            options={
                'db_table': 'empleados',
                'indexes': [models.Index(fields=['email'], name='empleados_email_idx'), models.Index(fields=['rol'], name='empleados_rol_idx')],
            },
        ),
    ]
